table 'Churn Reduction %'
	lineageTag: d0fe2298-9f99-4831-b825-c82c25b341f8

	measure 'Churn Reduction % Value' = SELECTEDVALUE('Churn Reduction %'[Churn Reduction %], 10)
		formatString: 0
		lineageTag: 863dd410-2380-41d4-a526-aa23de14b82b

	column 'Churn Reduction %'
		formatString: 0
		lineageTag: f1277a78-7aad-4e1f-9d8d-cbb9471ba738
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Churn Reduction %' = calculated
		mode: import
		source = GENERATESERIES(0, 30, 5)

	annotation PBI_Id = 86b1a15a43d94dd0befba0c87828cd65

